#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'Herb Schilling',
 'author_email': 'hschilling@nasa.gov',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'Openmdao driver wrapper for the Ipopt optimization code',
 'download_url': '',
 'entry_points': '[openmdao.component]\nipoptdriver.ipoptdriver.IPOPTdriver=ipoptdriver.ipoptdriver:IPOPTdriver\n\n[openmdao.driver]\nipoptdriver.ipoptdriver.IPOPTdriver=ipoptdriver.ipoptdriver:IPOPTdriver\n\n[openmdao.container]\nipoptdriver.ipoptdriver.IPOPTdriver=ipoptdriver.ipoptdriver:IPOPTdriver',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': 'Apache License, Version 2.0',
 'maintainer': 'Herb Schilling',
 'maintainer_email': 'hschilling@nasa.gov',
 'name': 'ipoptdriver',
 'package_data': {'ipoptdriver': []},
 'package_dir': {'': 'src'},
 'packages': ['ipoptdriver'],
 'url': 'https://github.com/OpenMDAO-Plugins/ipoptdriver',
 'version': '0.13',
 'zip_safe': False}


setup(**kwargs)

